version: '3.3'

services:
  nginx:
    container_name: my-nginx-proxy
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react-app

  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-react-app
    ports:
      - "3001:80"

